/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import test.ProxyNetworkSetupTest;
import test.client.ClientAPIExample;
import test.receiver.ReceiverAPIExample;
import java.io.IOException;
import java.net.UnknownHostException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        // try{
        //     JOnion.main(args);
        // }catch(UnknownHostException e){
        //     System.out.println("cannot resolve a hostname to an IP address.");
        // }
        new ProxyNetworkSetupTest().main(args);

        try{
            new ClientAPIExample().main(args);
            new ReceiverAPIExample().main(args);
        }catch(IOException e){}
    }
}
